### ISSUE TITLE
Mosaic encoding

### ISSUE THREAD

**Issue by Martronic-SA** [plone/plone.app.mosaic#315] opened 2016-11-21 09:31 UTC
There must be somtehing wrong with tiles encoding:

I have customized a mosaic view with some text for my custom dexterity type.
Then I have saved the mosaic view so I can use it for other items of same type.

When I use the saved view to other items, there appears to be something wrong with encoding although everything is fine with original item.
I have this in my mosaic html template:

'< div class="mosaic-grid-cell mosaic-position-leftmost mosaic-width-quarter"
             data-grid='{"type": "cell", "info":{"xs": "true", "sm": "true", "lg": "true", "pos": {"x": 1, "width": 3}}}'>
          < div class="movable removable mosaic-tile mosaic-text-tile">
          < div class="mosaic-tile-content">
< p>Mise en scène< /p>
          < /div>
          < /div>
        < /div>'

But it's rendered like that:

Mise en scÃ¨ne

Any hint?

Thank you!

**Comment by datakurre** [comment] 2016-11-23 03:20
@Martronic-SA Thanks for the report. Which versions are you using?

Could you provide a complete minimal example layout, which fails?

This should be easy fix, one we find the cause.

**Comment by Martronic-SA** [comment] 2016-11-24 09:08
plone.app.blocks 4.0.0rc1
plone.app.mosaic 2.0.0rc2
plone.app.standardtiles 2.0.0rc1
plone.app.tiles 3.0.0

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" data-layout="./@@page-site-layout">
  <body>
    <div data-panel="content"         data-max-columns="4">
      <div class="mosaic-grid-row">
        <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
          <div class="movable removable mosaic-tile mosaic-IDublinCore-title-tile">
          <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.field?field=IDublinCore-title"></div>
          </div>
          </div>
        </div>
      </div>
      <div class="mosaic-grid-row">
        <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
          <div class="movable removable mosaic-tile mosaic-IDublinCore-description-tile">
          <div class="mosaic-tile-content">
          <div data-tile="./@@plone.app.standardtiles.field?field=IDublinCore-description"></div>
          </div>
          </div>
        </div>
      </div>
      <div class="mosaic-grid-row">
        <div class="mosaic-grid-cell mosaic-width-full mosaic-position-leftmost">
          <div class="movable removable mosaic-tile mosaic-text-tile">
          <div class="mosaic-tile-content">
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div class="temp_html_tag">
<div class="temp_head_tag"> </div>
<p>Éléphant</p>
</div>
</body>
</html>
          </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
`

**Comment by datakurre** [comment] 2016-11-27 11:33
@Martronic-SA Thanks. I was able to reproduce it at http://ploneappmosaic200rc3.herokuapp.com/Plone/encoding-test

This definitely helps locating the issue and fixing it. It's too easy to get this kind of issues with Python 2 :/

**Comment by datakurre** [comment] 2016-11-27 12:36
Fixed in https://github.com/plone/plone.app.blocks/commit/6fb7ea5794491829ac6dc47b7a07f3d245ecdbb0

Will be fixed with pin plone.app.blocks = 4.0.0rc3 to be released later today.

**Closed** 2016-11-27 12:36 UTC
Labels: 01 type: bug, 11 prio: blocker

**Comment by Martronic-SA** [comment] 2016-12-02 09:41
Perfect, that's working!

Thank you
