### ISSUE TITLE
User should be able to customize selected content layout

### ISSUE THREAD

**Issue by vangheem** [plone/plone.app.mosaic#108] opened 2015-08-07 14:42 UTC
It seems to me that there is no way to change the content layout used. 

1. content is created
2. default layout value is set on creation
3. user can then change selected layout
4. since the layout value is stored on the content from the 2 previous steps, the new layout does not ever get activated

Am I missing something here?

Seems to me like I should not be using the view_methods FTI information (with aliases) to provide more layout options.

There should be something in the mosaic editor to select the "custom layout" for it and then some sort of tile merging and a warning to the user.

Also, before you start editing content, you should select the layout.

This line is also problematic: https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/widget.py#L52

I feel like I'm mis-understanding how layouts are supposed to be integrated here though.

Thoughts?

**Comment by vangheem** [comment] 2015-08-07 14:56
The use-case important to me right now is 1) admins being able to create content layouts TTW and 2) users being to select and use those layouts.

**Comment by datakurre** [comment] 2015-08-07 16:48
@vangheem You observations are correct. I'll explain a it later in detail.

**Comment by datakurre** [comment] 2015-08-07 17:08
@vangheem You are using everything correctly, as designed so far.

There are two basic use cases in Mosaic:

– Use layout editor to design new named static views for DX types TTW.
– Let editor to design custom layout.

And yes, we are missing a bridge between these. According to the legacy codebase, the original Deco editor had action for "loading layout". I think, it simply replaced everything in layout editor with predefined layout. This is not yet implemented in Mosaic.

I'm open for all suggestions and pulls about how this should work UX wise. E.g. should we hide "Custom layout" in the beginning and only enable it, when user has selected his/her favourite layout and clicks "Customize layout" somewhere? Then hide it again when something else is selected and simply override the custom layout after each "Customize" action?

About the problematic line. At Barcelona Sprint it was required that the layout widget should only be active when the content object has "Custom layout" enabled. It is a hack. Better ideas welcome. The custom layout view is named just "view" and registered for layout behavior in plone.app.blocks to be active OOTB for TTW dexterity types with layout behavior.

**Comment by vangheem** [comment] 2015-08-07 17:17
Alright, I'm going to think about this and try to come up with a solution. Thanks for confirming my assessment.

I see it working like this:

- Only one display menu entry. Not sure if we should keep the name "Custom layout" or if there is something better
- content starts off with no layout defined
- on creation, you select from available layouts(handled by mosaic editor)
- layouts should be able to be restricted to certain types still. Defined in manifest
- layouts should be able to have preview images in manifest
- remove "variant" feature in manifest. It's a bit odd and unnecessary I think.
- can change existing layout through mosaic editor
- attempt to do tile merging when changing layouts

**Comment by datakurre** [comment] 2015-08-07 17:53
Nathan Van Gheem wrote:
> * Only one display menu entry. Not sure if we should keep the name
>   "Custom layout" or if there is something better

You can achieve this simply by configuring "view" to be the only allowed 
view for the type in FTI.

> * content starts off with no layout defined
> * on creation, you select from available layouts(handled by mosaic editor)
> * can change existing layout through mosaic editor

Wouldn't it be easier to keep using the default alias mapping (could 
still allow only "view" in available display views), and only implement 
menu to change the content layout?

> * layouts should be able to be restricted to certain types still.
>   Defined in manifest
> * layouts should be able to have preview images in manifest
> * remove "variant" feature in manifest. It's a bit odd and unnecessary
>   I think.

+1 for these

Content type restriction could be achieved already with FTI method 
aliases, but having them in manifest makes more sense.

p.resource Manifest support is such that without "variants" you can only 
have one layout per p.resource directory. Yet, variants did introduce 
more problems than they solved. (We will also need localizations for 
layout titles in manifests and that's much easier when there's only a 
manifest per layout).

>   * attempt to do tile merging when changing layouts

Minimal would be to just copy user-added tiles from the old layout to 
the new layout. Yet, currently the only way to detect them might be that 
they have UUID in their URLs (that UUID only matters for persistent tiles).

**Comment by vangheem** [comment] 2015-08-07 21:26
I don't like the idea of having additional layouts in the display menu. IMO, they should be managed/changed with the mosaic editor.

**Comment by datakurre** [comment] 2015-08-07 22:20
@vangheem Ok. Maybe we could then just pretend that there was no layouts in the display menu. Simply leave "Available view methods" to just "view" and there should be only the "Custom layout" view with Mosaic editor enabled (I think, at least Plone 4 did hide the display menu when there was no other options). Then you could just implement layout changing into the editor (and not bother about the optional display menu support).

**Comment by vangheem** [comment] 2015-08-07 22:32
Yes, that is exactly what I was trying to describe :)

**Comment by datakurre** [comment] 2015-08-14 05:13
This use-case could now be turned into the default behavior with https://github.com/plone/plone.app.mosaic/pull/119

1. content is created
2. default panel fill layouts are set on creation
3. user can then change selected layout in panels
4. user change layout from display menu
5. saved panel fill layouts will be used to fill similarly named panels on the selected layout
6. back to 3.

Even with this, it would still be very nice to have your layout pre-set loading / saving in the layout editor.

**Comment by vangheem** [comment] 2015-08-17 15:41
I'm a bit confused on what is going on with the panel work. It seems like I should drop this branch since you'd prefer to keep going using the display drop down with content type aliases to select layout.

Moreover, it's becoming more obvious that mosiac won't be able to hit my use-case. At least not in a way that seems sane to me. I need static layouts with tiles where the layouts can be changed centrally and it updates the layouts of all the content using that layout. 

If you're interested, I'm going to look into a different implementation outside of mosaic that allows storage tile configuration outside of the layout.

**Comment by datakurre** [comment] 2015-08-17 15:47
@vangheem Could you elaborate more, which parts should be static (centrally) and which customizable (for each content instance)? I don't understand what is missing in Mosaic.

**Comment by datakurre** [comment] 2015-08-17 15:50
Panels are slots for instance specific content. Layouts may have tiles outside slots (static and centrally managed) and define default content for slots. When layout is being rendered, slots are being filled from content instance specific (from the data created with Mosaic Editor). Tiles can be everywhere, because they are only interpolated after panels have been merged.

**Comment by vangheem** [comment] 2015-08-17 16:04
mosaic stores the layout on the content object. When you change the layout, it does not store the actual layout used. Say you have 1000 pages with content layout "X". Then you want update content layout "X". Well, you need to go through all your content and somehow update? Merge tiles? I dunno, it's messy and not really something you should do. 

I don't understand how panels help me at all. How is the data stored? How are they updated? Moreover, the stack is just getting way too complicated to follow when you put so many of these transforms on top of each other. Diazo, panels, content layouts, site layout, page layout--just too much. Maybe I could go all in and drop diazo but I still don't see how any of this addresses the problem I mentioned above.

**Comment by vangheem** [comment] 2015-08-17 16:11
The more I dig into this, the more I think mosaic should have 2 modes:

1) custom layout, tile configuration stored on layout, only update with mosaic editor
2) static layout, tile configuration storage in persistent mapping on object apart from the layout, tiles have some sort of id so storage and rendering match, layout can change and it'll update all content with that layout selected. So you still utilize tiles but have layouts that can be centrally managed and it's not a nightmare to deal with existing content.

**Comment by datakurre** [comment] 2015-08-17 16:41
@vangheem I thought that we already had exactly those two modes when you began to work with Mosaic? Which part I'm not understanding and which part is really missing?

You started with centrally managed "content layouts" mapped for content types with those ++static++something mappins in FTI. I thought that would have been use case 2). You wanted something else, and I didn't really understand.

Then there was (on by default, but optional) "Custom layout", just like use case 1).

I still think that blocks rendering model is really simple and clean. All the complexity in Mosaic comes from making it backwards compatible with the existing Plone UI and expected features (like body tag).

**Comment by vangheem** [comment] 2015-08-17 16:48
With the current model, how would we ever change an existing layout? What I was going to attempt to do was allow a user to select a layout and then change layouts afterward. With that, you also need to get rid of the dsiplay menu(but it seems like you do not agree?).

However, the way it's implemented is that it saves the whole layout on the content object. It's essentially a copy every time. If you have 100 object thats were created initially with some layout, editing the original layout does NOT change the 100 objects that used that layout to base their layout on previously. In other words, every single object has a unique layout instance. You just have base layouts to start off with. This is necessary because all tile configuration is done IN the layout.

If we're in agreement for the 2 use-cases for layouts, we'll need to change the way the tile configuration is stored and NOT store the layout on the content object when working with use-case #2.

**Comment by djay** [comment] 2015-08-17 16:50
Sounds we need to go through and list all the problems mosaic is trying to
solve and then work out which is the most important one.
Problems before solutions.

**Comment by datakurre** [comment] 2015-08-17 20:18
@vangheem If customizing the editor to work with static layouts looks too daunting, and you are not completely fed up with my talk about panels, there could still be an alernative way with my branch, with support for inline editable text tiles.

If you try my branch, define a content without any panels. That should make it completely static. Now, add data-panel with unique name for each rich text area. Those should turn into editable areas in Mosaic editor (and during save, those would be saved into content). What is missing, is edit support for tiles in those static areas, but it might be fixable with only tweaking some selectors. (Also note that there is no add form support.)

Nathan Van Gheem kirjoitti ma elokuuta 17 19:48:42 2015 GMT+0300:

**Comment by hvelarde** [comment] 2015-08-18 00:47
@datakurre @vangheem be careful, listen to @djay and don't try to make Mosaic collective.cover light: the original Deco concept has no such use case.

what you are trying to do, Nathan, is a use case covered in collective.cover.

**Comment by datakurre** [comment] 2015-08-18 06:24
Since the Barcelona sprint, I've had two use cases for Mosaic: 1) centrally managed TTW views for Dexterity types and 2) content instance specific custom layouts; both compatible with both the legacy main_template based rendering and Blocks' site layout based rendering (for Deco like aite layout management).

Deco never really got beyond 2). It had plone.app.page with one default layout per "page category" FTI no any kind of central management for page/content layouts. Also Deco manifest didn't cover structured content (Page had only title, decscription and layout).

For me, Nathan's use-case is like 1) and could fix the discontinuation in current implementation between 1) and 2).

**Comment by datakurre** [comment] 2015-08-18 06:37
To distiguish from cover, cover like p.a.page has set of initial default layouts, but does not provide centrally managed layouts that could be updated later and have immediate effect on all existing content.

**Comment by agitator** [comment] 2015-08-18 07:01
1. usecase is basically a replacement for the single richtext field and imho works great if you see it like that
2. additional centralized manage of contenttype layouts would be really nice, for example to just add another column to all of the "pages"

@datakurre wasn't 2 what you suggested to (mis)use site layouts for in my case?

**Comment by datakurre** [comment] 2015-08-18 07:45
@agitator Currently 2. is supported with completely static layouts, and we are still figuring out the best way to make it more flexible. I think, your and Nathan's use-cases are very close.

About site layouts. I don't think that having content-type or view specific site layouts woudl have been mis-use. In the Deco vision the site layouts would be simple enough that having a lot of them would not be an issue. Yet as long as we a trying to replicate the complete main_template, site layouts remain too complex.

@vangheem I was wrong about my branch earlier. Static parts of layouts are already rendered there and cannot be trivially invoked to be editable. Continuing to thing about this... just too close to drop this :)

**Comment by vangheem** [comment] 2015-08-18 18:41
@datakurre current status:

- branch is at: https://github.com/plone/plone.app.mosaic/tree/content-layout-fixes
- blocks branch too: https://github.com/plone/plone.app.blocks/commit/991ea97db7411da9b1ae2f40b014db077821eec2
- video of current status: https://www.dropbox.com/s/qd0gxanq35xc28h/example-new-layout-edit.mov?dl=0

What is done:

- can select content layout
- can customize content layout
- can switch content layouts

What is not done:

- static layout tile configuration should NOT be transient
- nicer layout selector

**Comment by datakurre** [comment] 2015-08-18 18:59
@vangheem

- Mosaic Editor layout selector look great! (You probably noticed from registry configuration that something similar was planned also into Deco.) 
- This was my idea about forcing transient tiles to use persistent data (yet, tests are broken for the branch) https://github.com/plone/plone.tiles/commit/25a6252fe4102143076a0814ae198d9e7d254d33
- I still don't understand, what was wrong in using FTI configuration and display menu for selecting static layout? (And why it should be replaced with additional field in behavior.)

**Comment by vangheem** [comment] 2015-08-18 19:11
@datakurre 

I guess there is nothing necessarily wrong in using the display menu but you have to do a lot of configuration management to make it work. Additionally, you need menu and traverser customizations to make it work which seem a bit wonky.

I don't necessarily like that I put the additional field on the behavior but it seemed like the best way.

I also prefer that the layout editor controls it all instead of using the display menu. I was also planning the ability for layouts to have screenshots or icons associated with them so the layout selector will be nicer that way.

**Comment by datakurre** [comment] 2015-08-18 19:30
@vangheem Thanks. I understand now, and don't slow you down anymore. Simpler is usually better, so I need to take some distance to be able to kill my darlings :) Let's see later, how to finish that plone.tiles manager...

**Comment by datakurre** [comment] 2015-08-19 08:24
@vangheem Does you have plan, how to define "default static layouts" for content types?

**Comment by vangheem** [comment] 2015-08-19 21:39
Some of these things aren't completely clear for me yet.

- Yes, manifests will be connecting content types to layouts
- I think we still need default layout support so I might add that back in. The reason we need it is that if you change the default view of a content object to the mosaic view after there are already content objects on the site, your view will be empty because you were never able to choose a layout for it.

**Comment by vangheem** [comment] 2015-08-21 21:55
This is pretty close now.

Default layouts can now be set with a registry setting and all the things we talked about are implemented. A bunch of tests are failing now but I'm ready for some more review of what you think about the changes.

Here are my current branches(hopefully I didn't forget anything):

```
plone.app.mosaic = git ${remotes:plone}/plone.app.mosaic.git pushurl=${remotes:plone_push}/plone.app.mosaic.git branch=content-layout-fixes
plone.app.standardtiles = git ${remotes:plone}/plone.app.standardtiles.git pushurl=${remotes:plone_push}/plone.app.standardtiles.git branch=add-rich-text-tile
plone.tiles = git ${remotes:plone}/plone.tiles.git pushurl=${remotes:plone_push}/plone.tiles.git branch=datakurre-transient-to-persistent
plone.app.blocks = git ${remotes:plone}/plone.app.blocks.git pushurl=${remotes:plone_push}/plone.app.blocks.git branch=static-layouts
```

**Comment by datakurre** [comment] 2015-08-22 06:33
Thanks. Got all running (on Plone 4, of course ;) and slowly going through everything during weekend. Probably I'd like to keep displaymenu code for a while (yet keep its configuration empty) and remove it later in a single commit (for a better history).

**Comment by vangheem** [comment] 2015-08-22 09:06
I can squash all the commits on the branch.

**Comment by datakurre** [comment] 2015-08-22 17:01
Btw, I appreciate how you managed to simplify Mosaic UX.

**Comment by datakurre** [comment] 2015-09-18 10:42
Merged into master some time ago.

**Closed by datakurre** 2015-09-18 10:42 UTC
Labels: enhancement
