### ISSUE TITLE
p.a.mosaic 3.0.x, Plone 6.0.2 TinyMCE does half of the time not get initialised in tile edit modals

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.mosaic#528] opened 2023-03-13 20:16 UTC
In  a project I am upgrading from Plone 5.2. to Plone 6.0 we have some custom tiles with multiple RichText fields. Sometimes, about 50% the tinymce doesn't get initialised for any of the richtext fields in the browser and you only see the mimetypeselector:

<img width="837" alt="tinymce richtextfieldwidget" src="https://user-images.githubusercontent.com/394784/224817780-7f90f077-3f53-43a4-9f35-d0ac896fa313.png">

When reloading loading the mosaic edit page and again clicking on the edit, shows a completely random but about 40-60% chance of tinymce loading.  If I also keep the network tab open in the browser and monitor loaded js resources, the  times the initialisation fails, I consistently see a failed 404 request for:

`http://localhost:8080/nl/++webresource++fd4360ae-bfad-5886-999c-a1c8440f3377/++plone++static/bundle-plone/chunks/themes/silver/theme.min.js%E2%80%9D`

If I don't see the error that this resources cannot be loaded, TinyMCE works.  According to @petschki  who assisted me with some debugging on Discord, this separate resource has been removed from the tinymce pattern and should be loaded directly.  -> https://github.com/plone/mockup/blob/master/src/pat/tinymce/tinymce--implementation.js#L168

----

Digging further, I can check the initiator and stack trace of the silver/theme.min.js chunk that's no longer there: 

<img width="1292" alt="stack-trace-wrong-resource-load" src="https://user-images.githubusercontent.com/394784/224818766-cdabce76-9abb-4276-a0ef-194e629dfbad.png">

From that stack trace I can jump to the exact line that inserts/starts the load, which is here.  If I put a breakpoint on that line and reload the page a few times, every time I hit the breakpoint and the passed resource to load is the silver/theme.min.js the tinymce init will fail when I resume from the breakpoint

<img width="1627" alt="tinymce-breakpoint-themeresourceload" src="https://user-images.githubusercontent.com/394784/224819194-89fe7624-2ab7-43a2-9493-e913d2c06798.png">

Also a bit surprising, half of the times when refreshing the page, the breakpoint on the line to load the resource will instead show this resource to load, nd then tinymce initialisation works. 

`http://localhost:8080/nl/++webresource++fd4360ae-bfad-5886-999c-a1c8440f3377/++plone++static/bundle-plone/chunks/langs/nl.js`

----

## Possibly releated issues

* This issue was opened in January by @frapell where he describes that tinynmce chunks get reloaded when they should already be present in the browser.  With the behaviors descrribed above it also seems like non deterministically 'old' or different versions of tinymce get loaded. 
https://github.com/plone/plone.app.mosaic/issues/515

I tried to debug this by having 2 browser windows opened on the network tab, filtering on .min.js javascript resources and creating a working and non working reload next to each other. Then I sorted on the filename and compared EACH of the 50-60 resources. ALL THE SAME chunks get loaded, only the extra silver/theme.min.js 404 is present in the browser network list where TinyMCE doesn't initialise in the modal. 

That seems to bust the theory that a different tinymce gets loaded, but the ordering is somewhat different in each browser refresh, so a race condition could still be there depending on the loading order and that tinymce's from both bundles (mosaic-remote and plone-bundle-remote) get loaded always. 

* So checking if/how resources are maybe cached,  there is the following now closed issue, it seems to have been implemented by @jensens, but I cannot find the proposed function or a cache busting system in the current implementation:
https://github.com/plone/Products.CMFPlone/issues/3505

* There is this issue of the editor not working and suddenly started to work after restarts:  https://github.com/plone/plone.app.mosaic/issues/524

* I tried to regenerate the plone.app.mosaic resources, but the 3.0.x branch is currently broken as it depends on a select2.patch file which is not in the released @plone/mockup 5.0.5 
https://github.com/plone/plone.app.mosaic/issues/527

@jensens @thet   Something is going on here, but I can't get my digital finger on it yet.

**Comment by fredvd** [comment] 2023-03-13 20:38
One follow up. I did deploy the project to a testing environment.  In production mode, I never see the silver/theme.min.js being attempted to load with a 404 and the tinymce initialisation always succeeds.

Locally on my dev machine I have both branches of plone.staticresources 2.0.x and plone.app.mosaic 3.0.x checked out and that is where I see the failures happening, either in debug mode or in production mode locally. 

I get the feeling there is something wrong with the caches or with the chunks/generated webresources in the source checkouts  when running locally in development mode.   Unfortunately plone.app.mosaic doesn't build the resources locally at the moment (#527)

**Comment by jensens** [comment] 2023-03-14 17:18
Some month ago with 6.0.0 I had the same effect, but it seems to be gone now, so I was the opinion its solved.
Wild guesses what could be wrong:
- do we have async loading here and a timing problem?
- are the chunks fine and loaded in order?

Moreover, webresource is a dumb piece of software, creating a dependency tree of the resources given, calculating a hash to insert in the URL and delivering a HTML snippet. That is it.

**Comment by petschki** [comment] 2023-04-21 11:02
So if I understand correctly there are actually two different issues here: fred initially talked about TinyMCE within modals not showing up -> this is caused by `pat-textareamimetypeselector` which I think I fixed here: https://github.com/plone/mockup/pull/1309

The second issue by @mauritsvanrees  that the inline editor toolbar not showing up randomly is something different and I need to dig through mosaics tiny initialization process ...

**Comment by thet** [comment] 2023-04-21 12:03
I‌ have another PR which might help here:
https://github.com/plone/plone.app.mosaic/pull/535

And another problem:
https://github.com/plone/plone.app.mosaic/issues/536
Can anyone confirm the problem? @petschki @fredvd @frapell ?

**Comment by petschki** [comment] 2023-06-02 05:45
Latest releases in `https://dist.plone.org/release/6.0.5/versions-ecosystem.cfg` should fix this issue. Feedback welcome.

**Comment by petschki** [comment] 2023-07-04 07:48
Since Plone 6.0.6 we have switched to  mosaic 3.1.x which should have fixed those problems permanently. @fredvd I'll close this ticket, but feel free to reopen or open a new one if you have still problems.

**Closed by petschki** 2023-07-04 07:48 UTC
