### ISSUE TITLE
RichText tile: popup opens with table properties!?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.mosaic#364] opened 2017-05-28 09:45 UTC
Plone 5.1b3
p.a.m. 2.0rc5

I added a RichText title, marked some text and click on the right mouse button...why do I see table properties?

![screenshot-dev zopyx de-12020-2017-05-28-11-43-37](https://cloud.githubusercontent.com/assets/594239/26527765/034f59e6-439b-11e7-9b88-a54f9d605b1e.png)

**Comment by tmassman** [comment] 2017-05-28 13:53
Can you reproduce the behaviour with non mosaic enabled content when highlighting text in TinyMCE?

**Comment by datakurre** [comment] 2017-05-28 15:41
Thank you!
Spark by Readdle

**Comment by datakurre** [comment] 2017-05-28 15:41
It's a broken default configuration for Mosaic. One of the reasons we still don't have 2.0 final...

A year ago there was a specific HTML table helper tile and that popup was configured for that tile only. Majority did not like those specific HTML tiles in Mosaic 1.x and they were merged. That popup is remain from that merge. Still unfixed.

**Closed** 2017-08-21 06:23 UTC
