### ISSUE TITLE
Support for "Sub-Columns"

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#240] opened 2016-08-22 17:19 UTC
Tried to create a page like this for a client, but couldn't because we don't have some sort of substructure for rows/columns.

This is for discussion at the Mephisto Sprint

![sub-columns](https://cloud.githubusercontent.com/assets/365761/17864029/85172cc2-689c-11e6-83fa-6aa3f0b78008.png)

probably related to #208

**Comment by vangheem** [comment] 2016-08-22 17:20
FWIW, how I do this right now is manually creating the layout. Then, you can still edit the tiles but you can't customization the layout and move stuff around with the editor.

**Comment by agitator** [comment] 2016-08-22 17:25
Did this in my first mosaic project, but need the customization. 
So doing it with some special listing-views in connection with the content-listing tile.

**Comment by datakurre** [comment] 2016-08-22 18:32
In some other issue we had in idea of keeping the default layout editor experience simple, but add a modifier key (like alt) to enable advanced grid management. I tried it in one project, where designer needed more control on row splits and it kinda worked (alt allowed to drag tiles to "empty new rows" where ever there was a suitable space in grid).

**Comment by agitator** [comment] 2016-08-22 22:37
sounds like a good idea!

**Comment by datakurre** [comment] 2016-09-08 23:41
Since this may not happen with the current editor, @agitator could document, how he did this with site layouts.

**Comment by frapell** [comment] 2017-07-12 20:04
Hey guys, were there any advances on this?

**Comment by datakurre** [comment] 2017-07-12 20:16
@frapell Building this complex layout is still not supported by the current editor. 

GSOC by @mikkohu is working on a so called "inline tiles", which allows dragging tiles into TinyMCE of text tile. It would allow bypassing the current grid limitations.

In production we do this with static layouts or site layouts.

**Comment by datakurre** [comment] 2017-07-12 20:28
@hvelarde I agree. It's just that the current version might be too hard to update, and I still have not had time to properly look at Rob Gietemas new version at plone-react.

**Comment by frapell** [comment] 2017-07-20 00:00
@datakurre I did an initial implementation in https://github.com/plone/plone.app.mosaic/tree/frapell-subcolumns branch, that at the moment fits my needs.

The idea is that when you have the tile floating next to your mouse pointer, you will then press "Ctrl" (Not sure if OSX would have Cmd mapped as keycode 17), and then you drop it over an existing tile (only direction bottom really works).

At this point, the tile would be wrapped inside a mosaic-grid-cell and this creates the desired behavior (at least as described by @agitator when he opened the issue). Then you can start adding more tiles without the need to press Ctrl since the inner columns already exist.

The implementation still lacks a lot to be mergable, like visual feedback on what's going on, and also to alow further tiles to be added right below it (inside the same row)... However I wanted to first check with you if I should spend more time into improving this to a point that it can be included? or do you want to go completely in some other direction...



In addition (Unrelated to this particular issue), I wanted to ask, how are you compiling the JS resources? When I do it with 

```
./bin/plone-compile-resources --bundle mosaic
```

I get

```
Running "less:mosaic" (less) task
>> NameError: variable @barcelonetaPath is undefined in /vagrant/src/plone.app.mosaic/src/plone/app/mosaic/browser/static/css/mosaic.grid.less on line 1, column 21:
>> 1 @import (reference) "@{barcelonetaPath}/less/variables.plone.less";
>> 2 @import (reference) "@{barcelonetaPath}/less/mixin.grid.plone.less";
Warning: Error compiling /vagrant/src/plone.app.mosaic/src/plone/app/mosaic/browser/static/css/mosaic.pattern.less Use --force to continue.

Aborted due to warnings.
Traceback (most recent call last):
  File "./bin/plone-compile-resources", line 239, in <module>
    sys.exit(Products.CMFPlone._scripts.compile_resources.main())
  File "/usr/local/plone/buildout-cache/eggs/Products.CMFPlone-5.0.7-py2.7.egg/Products/CMFPlone/_scripts/compile_resources.py", line 89, in main
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/grunt', '--gruntfile=/vagrant/Gruntfile.js', 'compile-mosaic']' returned non-zero exit status 6
```

And so, I need to manually set the barcelonetaPath less variable with \"{site_url}/++theme++barceloneta\" as value in the resource registry, and then try again...

**Comment by djay** [comment] 2017-07-20 03:08
@frapell do you have a gif or screencast? Trying to understand how this will interact with @mikkohu work. His implementation works by hovering over a richtext tile and then the mode switches to be able to insert "inline". That means no grid. This seems to overlap a lot and I'm trying to think how to make this less confusing between these two modes. 
Also I'm not sold on key modifiers. It's not that discoverable so if there is a more on-screen way, that would be preferable.

Lastly, just to be clear, the usecase that is trying to be solved is the middle-left tile in the image above which has 2x2 grid inside a cell labeled "content listing"? So in that case the problem that needs to be solved is even more complex, since its not a matter of manually placing the 2x2 tiles right? This seems to overlap even more with the custom listing work. Would have to consider how to make subcolumns work with the new listing tile (which currently assumes its a richtext tile with inline tiles that get repeated).

**Comment by datakurre** [comment] 2017-07-20 07:13
@frapell ./plone-compile-resources really does not have barcelonetaPath set? Or where does the other bundles read it with plone-compile-resources?

So, we have at least four ways of compiling resources :) TTW, plone-compile-resources, mockup make and then just something within package.

**Comment by agitator** [comment] 2017-07-20 12:53
Plone master has the ``barcelonetaPath``  the compiled  ``Gruntfile.js`` within the ``modifyVars``.

**Comment by frapell** [comment] 2017-07-20 13:19
@djay I created a screencast of it here https://www.dropbox.com/s/uq4f5qka5sxj37r/inner_columns.mp4?dl=0

Yeah, I agree with you on key modifiers, however it could work fine with good visual feedback... for instance, when you have the tile hovering following the mouse an unobtrusive alert could popup at the top of the page with "Tip: Hold Ctrl for creating inline columns" or something like that... and of course improve the grid dotted lines that appear while you do that, to make it super clear what's happening...

As per the use case, the idea is to have inner columns. Right now, you cannot have columns at the sides, without affecting the rest of the layout (Basically, I would like the portlets functionality, without using portlets)

@datakurre @agitator Yeah, I tried compiling it in a 5.0.7 instance, and I just tried on latest 5.0 branch for coredev, and the same error happens.

**Comment by djay** [comment] 2017-07-20 18:19
What if you had a subgrid tile instead? That would be more explicit, discoverable and could use the same mechanism to insert an inline tile (hover then drop). That also gives it a border and perhaps way to drag it. The other reason to consider it is the case of making a repeating tiles. With a subgrid inside a tile, it can then have configuration. You can have two tiles, a subgrid tile and listing subgrid tile.

**Comment by datakurre** [comment] 2017-07-20 18:37
@frapell Could this work with the same modifier as the current "advanced" mode (the mode showing rows and allowing inserting new rows between rows). I recall it being alt and working on bit Linux and OSX. Also, when it's considered advanced, it doesn't need to be perfect right now. And possibly, we might protect advanced features with some permission later.

I have not needed this because I use site layouts, but I don't oppose this either. If you got it work safely, it's enough for me to support this :)

Grid tile would add a completely new concept into the editor. Layout could have options just by enhancing the editor. It would require work, but adding it to support new exceptional tile type would be even more work.

**Comment by frapell** [comment] 2017-07-20 19:20
@djay Well, at first I thought on doing it as a tile, however being that the layout structure is managed through Javascript entirely, I thought I might have stuff breaking when doing different actions (like adding, moving, etc...). Reading and understanding a bit what was going on, I realized that I only needed to wrap the added tile with the div.mosaic-grid-cell and that was it.

I might explore doing it as a tile and see how it goes...

@dataflake Well, the problem with Alt is that on Linux, you use it to drag a window without the need to do it from the title bar, so you cannot click while holding Alt.

Alright then, I'll try to advance with this, won't promise anything, but if I find the time to do it, I know it won't be rejected :)

**Comment by datakurre** [comment] 2017-07-20 19:46
@frapell Not on my Xmonad :), but because that's probably a common issue, maybe we should the make advanced mode work on both alt or ctrl?

**Comment by datakurre** [comment] 2017-07-20 19:50
@frapell I'd really prefer your option (merged into advanced mode) before tile one for simplicity. In theory it could look like a tile UI wise (usable from tile menu) while not really being a tile, but it would make the already complex tile handling code even more complex.

**Comment by frapell** [comment] 2017-07-20 19:50
Heh... I was going to clarify this was on KDE, and I think is the case on GNOME as well... Yeah, sounds nice, either Ctrl or Alt both enable advanced mode

**Comment by datakurre** [comment] 2017-07-20 20:05
@frapell Another nice feature would be to make advanced mode optionally sticky, like:

* short press (maybe < 400ms [1] of alt/ctrl) would simply toggle advanced mode on/off
* longer press would enable advanced mode on key down and disable advanced mode on key up

[1] https://stackoverflow.com/questions/22505698/what-is-a-typical-keypress-duration

**Comment by djay** [comment] 2017-07-21 03:02
My concern is to marry the concepts of mosaic supporting custom listings and this concept of sub cells. As soon as you have both it will be natural to say you want to automate the listing of a row of tiles, a vertical col of tiles, or even a wrapping row x col. 
Since @datakurre suggested not making listing part of mosaic layout directly but instead and do it as a tile (using inline tiles), I'm not yet seeing a natural way to support listing of grid tiles. Have to think on it more.

**Comment by frapell** [comment] 2017-07-24 15:54
Just commited some improvements, I think this pretty much done...

Screencast: https://www.dropbox.com/personal?preview=mosaic_inner_columns_2.mkv

@datakurre I remember why I added a second modifier key. It is so I can add these inner grids without the need to be in "Advance mode", and also be able to add tiles without inner grids, when in "Advance mode"...

I implemented your idea (Stick advance mode if tapping the Alt key, else keep it on while the key is pressed and disable when release), but I kept the ability to add an inner grid when pressing Ctrl.

I would love to include some way of letting the user know that they can add inner grids by pressing Ctrl (which I think should only show up when advanced mode is enabled). Maybe adding some text to the blue header while in advance mode?

@djay thoughts?

**Comment by datakurre** [comment] 2017-07-24 16:01
@frapell It seems that screencast was not public.

I believe this is ok, because without ctrl everything works as before. Yet, I am worried about having too modifiers.

I understand that the issue of "being able to add tiles without inner grids, when in "Advance mode"", but why was was too much to only be able to add inner grids in advanced mode? It feels advanced to me.

**Comment by frapell** [comment] 2017-07-24 16:06
@datakurre Sorry, this is the proper link https://www.dropbox.com/s/7gsy7uzcxs5skii/mosaic_inner_columns_2.mkv?dl=0


yeah, I think the problem is that "Advanced mode" maybe should be renamed to something like "detailed grid view" or something like that... I enable it when I want to see how the grid really looks like, but I want to be able to add these inner grids without seeing the "detailed grid view". Know what I mean?

**Comment by datakurre** [comment] 2017-07-24 16:52
@frapell Advanced mode also allows to add new rows between existing rows, which is not possible in default view. In default view new cells are always placed into existing rows when possible.

But as I said, I don't think CTRL is a blocker, but possibly we figure out a way to work without it later. For example: maybe keeping tile floating on top of a full width cell for a few seconds would allow to place it next to it by wrapping it with innergrid-row. But with such implicit behavior would also require innergrid rows to be removed when they are no longer needed. In any case, it would be more code than your explicit CTRL-action.

**Comment by datakurre** [comment] 2017-07-24 16:53
Oh, and thank you! I see now that this allow much more flexible layouts than without this.

**Comment by frapell** [comment] 2017-07-24 18:02
@dataflake Glad you like it :)

Here's the PR: https://github.com/plone/plone.app.mosaic/pull/371

**Closed** 2017-07-26 22:07 UTC
Labels: 04 type: enhancement
