### ISSUE TITLE
3.0.x branch: yarn start no longer works, missing select2.patch from @plone/mockup

### ISSUE THREAD

**Issue by fredvd** [plone/plone.app.mosaic#527] opened 2023-03-13 19:52 UTC
When I run `yarn install' in the plone.app.mosaic root to develop/test the js/css resources, I get the error below.  

Inspecting @plone/mockup 5.0.5 ( which is a dependency in package.json) on npmjs.com shows that indeed it has no patches directory in the npm packages.  The directory is also missing in ./node_modules/@plone/mockup

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open <project_buildout>develop/plone.app.mosaic/node_modules/@plone/mockup/patches/select2.patch'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '<project_buildout>/develop/plone.app.mosaic/node_modules/@plone/mockup/patches/select2.patch'
}
```

**Comment by petschki** [comment] 2023-03-13 21:25
I cannot reproduce this. A fresh `3.0.x` checkout with `yarn install && yarn start` works here without errors.

node version: v16.14.0 (and v18.15.0)
yarn version: 1.22.19

**Comment by fredvd** [comment] 2023-03-13 21:56
Found the cause, my default yarn version was 3.  I pinned the workspac to yarn@1 and yarn install now works. Should we update to yarn 3?  ;-)

**Comment by petschki** [comment] 2023-03-22 11:48
so we can close this, right?

**Closed by petschki** 2023-03-22 11:48 UTC
