### ISSUE TITLE
Display Tile Type on hover and/or select

### ISSUE THREAD

**Issue by agitator** [plone/plone.app.mosaic#39] opened 2015-04-10 15:26 UTC

**Comment by datakurre** [comment] 2015-04-11 08:38
This may be duplicate of #37

**Closed** 2015-05-03 02:00 UTC
Labels: enhancement

**Comment by datakurre** [comment] 2015-05-03 02:03
This was limited by purpose, but this change can easily be reverted later if required.

**Comment by datakurre** [comment] 2015-05-03 02:04
![nayttokuva 2015-05-03 kello 5 03 22](https://cloud.githubusercontent.com/assets/160447/7443425/ce1da126-f151-11e4-955e-6c53e77a1250.png)

**Comment by gforcada** [comment] 2015-05-03 10:50
Awesome!!

**Comment by simahawk** [comment] 2015-05-03 10:55
thanks asko! :)
